org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.2
minecraft_version_range=[26.2]
neo_version=26.2.0.72
loader_version_range=[1,)
jei_version=30.28.0.192
jade_version=26.2.10+neoforge

mod_id=agritechtwo
mod_name=Agritech
mod_license=MIT
mod_version=3.0.0.4+neoforge-mc-26.2
mod_group_id=com.misterd.agritechtwo
