org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.8-beta
loader_version_range=[1,)
jei_version=31.4.0.19
jade_version=26.3.1+neoforge

mod_id=agritechtwo
mod_name=Agritech
mod_license=MIT
mod_version=4.0.0.0+neoforge-mc-26.3
mod_group_id=com.misterd.agritechtwo
